site_name: Technical Writer Handbook
site_description: A handbook for technical writers
theme:
  name: material

nav:
  - Home: index.md

  - Getting started:
      - Overview: getting-started/index.md

  - Writing standards:
      - Overview: writing-standards/index.md
      - Voice and tone: writing-standards/voice-and-tone.md
      - Formatting: writing-standards/formatting.md

  - Documentation quality:
      - Markdownlint: documentation-quality/markdownlint.md
      - Vale: documentation-quality/vale.md

  - Glossary: glossary.md